const options = [
  {
    role: "buyer",
    id: "1",
    area: "San Francisco",
    budget: "600k",
    rooms: 2,
    bathrooms: 1.5,
    description: "preferably secluded, quiet, and near the beach",
    motivation:
      "recently immigrated to the US and looking for a place to settle down",
  },
  {
    role: "buyer",
    id: "2",
    area: "Bellingham",
    budget: "1 million",
    rooms: 3,
    bathrooms: 2,
    description: "preferably near the city center, close to the park",
    motivation: "looking for investments opportunities",
  },
  {
    role: "buyer",
    id: "3",
    area: "California",
    budget: "2 million",
    rooms: 4,
    bathrooms: 2,
    description: "preferably near a supermarket",
    motivation: "looking for a place to raise his family",
  },
  {
    role: "seller",
    id: "4",
    area: "Texas",
    minPrice: "1 million",
    rooms: 4,
    bathrooms: 2.5,
    yearBought: 2010,
    renovations: "no renovations",
    description: "near the lake",
    yearBuilt: 2000,
    motivation: "moving to a new city",
  },
  {
    role: "seller",
    id: "5",
    area: "Bellingham",
    minPrice: "900k",
    rooms: 3,
    bathrooms: 2,
    yearBought: 2020,
    renovations: "kitchen and bathroom renovated",
    description: "townhouse with new counter tops and cabinets",
    yearBuilt: 2018,
    motivation: "moving to a bigger house",
  },
  {
    role: "seller",
    id: "6",
    area: "Colorado",
    minPrice: "400k",
    rooms: 2,
    bathrooms: 2,
    yearBought: 2020,
    renovations:
      "apartment on the third floor with kitchen and bathroom renovated",
    description: "counter tops and cabinets are new",
    yearBuilt: 1990,
    motivation: "starting to work in a new city",
  },
  {
    role: "tenant",
    id: "7",
    area: "San Francisco",
    budget: "1.5k per month",
    rooms: 1,
    bathrooms: 1.5,
    description:
      "apartment on any floor except the first one. Preferably secluded, quiet, and near the beach",
    motivation: "single student looking for a place to stay",
  },
  {
    role: "tenant",
    id: "8",
    area: "Bellingham",
    budget: "2.4k per month",
    rooms: 3,
    bathrooms: 2,
    description: "preferably near the city center, close to the park",
    motivation: "looking for a place to stay with his family, new to the city",
  },
  {
    role: "tenant",
    id: "9",
    area: "California",
    budget: "3k per month",
    rooms: 4,
    bathrooms: 2,
    description: "preferably near a supermarket",
    motivation:
      "recently immigrated to the US and looking for a place to settle down",
  },
];

export { options };
